name: Deploy Streamlit App to Azure

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---- Login to Azure Container Registry ----
      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # ---- Build Docker Image ----
      - name: Build image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/url-spam-app:latest .

      # ---- Push Docker Image ----
      - name: Push image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/url-spam-app:latest

      # ---- Azure Login ----
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # ---- Deploy to Azure Web App ----
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "url-spam-classifier-deployment"
          images: ${{ secrets.ACR_LOGIN_SERVER }}/url-spam-app:latest
